"""Private storage and signed download links for order documents (PRD ТЗ№4 §81-83)."""

import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional

from jose import JWTError, jwt

from app.config import settings

ALLOWED_TYPES = {"application/pdf": ".pdf", "image/jpeg": ".jpg", "image/png": ".png"}
MAX_BYTES = 10 * 1024 * 1024
LINK_MINUTES = 5


def storage_dir() -> Path:
    path = Path(settings.DOCUMENTS_DIR) if settings.DOCUMENTS_DIR else Path(__file__).resolve().parent.parent / "private_documents"
    path.mkdir(parents=True, exist_ok=True)
    return path


def matches_signature(content_type: str, data: bytes) -> bool:
    if content_type == "application/pdf":
        return data.startswith(b"%PDF-")
    if content_type == "image/jpeg":
        return data.startswith(b"\xff\xd8\xff")
    if content_type == "image/png":
        return data.startswith(b"\x89PNG\r\n\x1a\n")
    return False


def save(content_type: str, data: bytes) -> str:
    name = f"{uuid.uuid4().hex}{ALLOWED_TYPES[content_type]}"
    (storage_dir() / name).write_bytes(data)
    return name


def path_of(storage_name: str) -> Path:
    # storage_name is generated by save(); refuse anything that could leave the directory.
    if Path(storage_name).name != storage_name:
        raise ValueError("bad storage name")
    return storage_dir() / storage_name


def make_link_token(document_id: int) -> str:
    exp = datetime.now(timezone.utc) + timedelta(minutes=LINK_MINUTES)
    return jwt.encode({"doc": document_id, "exp": exp}, settings.SECRET_KEY, algorithm=settings.ALGORITHM)


def read_link_token(token: str) -> Optional[int]:
    try:
        claims = jwt.decode(token, settings.SECRET_KEY, algorithms=[settings.ALGORITHM])
    except JWTError:
        return None
    doc = claims.get("doc")
    return doc if isinstance(doc, int) else None
