"""Order documents generated by the platform itself (PRD ТЗ№1 §57): order confirmation, invoice, proforma
invoice and packing list. They are printable HTML pages (open, then Print > Save as PDF), stored like any other
order document so customers get them through the signed-link flow and they can be superseded by documents
the ERP issues later. Everything coming from the database is HTML-escaped.

Auto-generation (see generate_for_status): confirmation when an order is placed, proforma for company orders
that are still unpaid, invoice when it is paid, packing list when it is packed. Admins can regenerate any of them.
"""

import html
import logging
import uuid
from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.enums import OrderStatus
from app.models.order import Order, OrderType
from app.models.order_document import OrderDocument
from app.models.site_settings import SiteSettings
from app.models.sku import SKU
from app.services import documents
from app.services.packaging import packaging_for

logger = logging.getLogger("maru.documents")

GENERATED = "generated"  # OrderDocument.external_id marker for platform-made documents

TITLES = {
    "order_confirmation": ("Order confirmation", "OC"),
    "invoice": ("Invoice", "INV"),
    "proforma_invoice": ("Proforma invoice", "PRO"),
    "packing_list": ("Packing list", "PL"),
}

_CSS = """
body{font:14px/1.45 Arial,Helvetica,sans-serif;color:#111;margin:32px auto;max-width:800px;padding:0 16px}
h1{font-size:22px;margin:0 0 4px}.muted{color:#555}.row{display:flex;justify-content:space-between;gap:24px;margin:18px 0}
table{width:100%;border-collapse:collapse;margin:16px 0}th,td{border-bottom:1px solid #ddd;padding:6px 8px;text-align:left}
th{background:#f4f4f4}td.n,th.n{text-align:right}.totals{margin-left:auto;width:320px}.totals td{border:0;padding:3px 8px}
.totals tr.sum td{border-top:2px solid #111;font-weight:bold}.note{margin-top:24px;font-size:12px;color:#555}
@media print{body{margin:0}}
"""


def _e(value) -> str:
    return html.escape("" if value is None else str(value))


def _money(amount, currency) -> str:
    return f"{_e(currency)} {float(amount):,.2f}"


def _company(db: Session) -> dict:
    row = db.get(SiteSettings, 1)
    return {"phone": getattr(row, "phone", None), "email": getattr(row, "email", None), "address": getattr(row, "address", None)}


def document_number(doc_type: str, order: Order) -> str:
    return f"{TITLES[doc_type][1]}-{order.order_number}"


def render(db: Session, order: Order, doc_type: str) -> str:
    if doc_type not in TITLES:
        raise ValueError(f"Unknown document type {doc_type}")
    title = TITLES[doc_type][0]
    company = _company(db)
    created = (order.created_at or datetime.now(timezone.utc)).strftime("%Y-%m-%d")
    issued = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    is_company = order.order_type == OrderType.COMPANY

    bill_lines = [f"{order.first_name} {order.last_name}"]
    if is_company:
        bill_lines = [order.company_name or ""] + [f"Contact: {order.contact_person}" if order.contact_person else ""] + [
            f"Reg. no.: {order.company_reg_number}" if order.company_reg_number else "",
            f"Tax no.: {order.company_tax_number}" if order.company_tax_number else "",
            order.company_address or "",
        ]
    bill_lines += [order.email, order.phone]
    ship_lines = [f"{order.first_name} {order.last_name}", order.address_line, " ".join(x for x in (order.postal_code, order.city, order.region) if x), order.country]

    def block(label, lines):
        body = "<br>".join(_e(x) for x in lines if x)
        return f"<div><strong>{_e(label)}</strong><br>{body}</div>"

    if doc_type == "packing_list":
        skus = {i.id: db.get(SKU, i.sku_id) for i in order.items if i.sku_id is not None}
        pack = packaging_for((skus[i.id], i.quantity) for i in order.items if skus.get(i.id) is not None)
        head = "<tr><th>SKU</th><th>Product</th><th class=\"n\">Quantity</th></tr>"
        rows = "".join(
            f"<tr><td>{_e(i.sku_code_snapshot)}</td><td>{_e(i.product_name_snapshot)}"
            f"{' - ' + _e(i.variant_name_snapshot) if i.variant_name_snapshot else ''}</td><td class=\"n\">{i.quantity}</td></tr>"
            for i in order.items
        )
        d = pack.as_dict()
        summary = (
            f"<p><strong>Packing:</strong> {d['boxes']} box(es)"
            f"{(' + ' + str(d['loose_units']) + ' loose unit(s)') if d['loose_units'] else ''}, "
            f"approx. {d['weight_kg']} kg, {d['volume_l']} L{'' if d['complete'] else ' (estimate: some size/weight data is missing)'}.</p>"
        )
        totals = summary
        body_table = f"<table>{head}{rows}</table>"
    else:
        head = "<tr><th>SKU</th><th>Product</th><th class=\"n\">Qty</th><th class=\"n\">Unit price</th><th class=\"n\">Discount</th><th class=\"n\">Tax</th><th class=\"n\">Total</th></tr>"
        rows = "".join(
            f"<tr><td>{_e(i.sku_code_snapshot)}</td><td>{_e(i.product_name_snapshot)}"
            f"{' - ' + _e(i.variant_name_snapshot) if i.variant_name_snapshot else ''}</td><td class=\"n\">{i.quantity}</td>"
            f"<td class=\"n\">{_money(i.unit_price, i.currency)}</td><td class=\"n\">{_money(i.discount_amount or 0, i.currency)}</td>"
            f"<td class=\"n\">{_money(i.tax_amount or 0, i.currency)}</td><td class=\"n\">{_money(i.line_total, i.currency)}</td></tr>"
            for i in order.items
        )
        cur = order.currency
        totals = (
            "<table class=\"totals\">"
            f"<tr><td>Subtotal</td><td class=\"n\">{_money(order.subtotal_amount, cur)}</td></tr>"
            f"<tr><td>Discount</td><td class=\"n\">-{_money(order.discount_amount, cur)}</td></tr>"
            f"<tr><td>Tax</td><td class=\"n\">{_money(order.tax_amount, cur)}</td></tr>"
            f"<tr><td>Delivery</td><td class=\"n\">{_money(order.delivery_amount, cur)}</td></tr>"
            f"<tr class=\"sum\"><td>Total</td><td class=\"n\">{_money(order.total_amount, cur)}</td></tr></table>"
        )
        body_table = f"<table>{head}{rows}</table>"

    extra = ""
    if doc_type == "proforma_invoice":
        extra = "<p class=\"note\">This is a proforma invoice: a request for payment, not a tax document. The invoice is issued once the order is paid.</p>"
    elif doc_type == "invoice":
        extra = f"<p><strong>Payment:</strong> {_e(order.payment_method)} - {_e(order.payment_status.value if order.payment_status else '')}</p>"
    elif doc_type == "order_confirmation":
        extra = "<p class=\"note\">Thank you for your order. We will notify you as it progresses.</p>"

    seller = "<br>".join(_e(x) for x in ("MARU", company["address"], company["phone"], company["email"]) if x)
    return (
        "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">"
        f"<meta name=\"robots\" content=\"noindex,nofollow\"><title>{_e(title)} {_e(document_number(doc_type, order))}</title>"
        f"<style>{_CSS}</style></head><body>"
        f"<h1>{_e(title)}</h1><p class=\"muted\">No. {_e(document_number(doc_type, order))} &middot; order {_e(order.order_number)} "
        f"placed {_e(created)} &middot; issued {_e(issued)}</p>"
        f"<div class=\"row\">{block('Seller', seller.split('<br>'))}{block('Bill to', bill_lines)}"
        f"{block('Deliver to', ship_lines) if doc_type == 'packing_list' or order.delivery_method else ''}</div>"
        f"{body_table}{totals}{extra}</body></html>"
    )


def generate(db: Session, order: Order, doc_type: str, actor=None, replace: bool = True) -> OrderDocument:
    """Renders the document and stores it. With replace=True an earlier generated copy of the same type is
    voided so the customer sees one current document. Caller commits."""
    existing = db.execute(
        select(OrderDocument).where(
            OrderDocument.order_id == order.id, OrderDocument.doc_type == doc_type,
            OrderDocument.external_id == GENERATED, OrderDocument.status == "issued",
        )
    ).scalars().all()
    if existing and not replace:
        return existing[0]
    for old in existing:
        old.status = "void"
    content = render(db, order, doc_type).encode("utf-8")
    name = documents.save_html(content)
    doc = OrderDocument(
        order_id=order.id, doc_type=doc_type, status="issued", external_id=GENERATED,
        filename=f"{document_number(doc_type, order)}.html", storage_name=name, content_type="text/html", size_bytes=len(content),
    )
    db.add(doc)
    db.flush()
    return doc


def generate_for_status(db: Session, order: Order, status: Optional[OrderStatus]) -> None:
    """Auto-generation hook. `status` None means "order just placed". Never raises."""
    try:
        wanted: list = []
        if status is None:
            wanted.append("order_confirmation")
            if order.order_type == OrderType.COMPANY:
                wanted.append("proforma_invoice")
        elif status == OrderStatus.PAID:
            wanted.append("invoice")
        elif status == OrderStatus.PACKED:
            wanted.append("packing_list")
        for doc_type in wanted:
            generate(db, order, doc_type, replace=False)
        if wanted:
            db.commit()
    except Exception:  # noqa: BLE001 - a document problem must never fail the order
        logger.exception("Could not generate documents for order %s", getattr(order, "id", "?"))
        db.rollback()


__all__ = ["generate", "generate_for_status", "render", "TITLES", "GENERATED", "uuid"]
