import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    // sitemap.xml is generated by the backend (needs DB access for the
    // product/blog list) — proxy it here so it's reachable at the
    // frontend's own origin in dev, matching how a production reverse
    // proxy needs to route it (see app/main.py's sitemap() docstring).
    proxy: {
      '/sitemap.xml': 'http://127.0.0.1:8000',
    },
  },
})
